"use client";

import { FileDown } from "lucide-react";

type Guest = {
  id: string;
  first_name?: string;
  last_name?: string;
  name?: string;
  email?: string | null;
  status?: string;
  journey_stage?: string;
  journeyStage?: string;
  visit_date?: string;
  created_date?: string;
  createdAt?: string;
  is_at_risk?: boolean;
  isAtRisk?: boolean;
};

type Props = {
  guests: unknown[];
  careNotes: unknown[];
  retentionRate: number;
  atRiskCount: number;
  stageData: { name: string; value: number }[];
  statusData: { name: string; value: number }[];
};

function buildPrintHtml(
  guests: Guest[],
  retentionRate: number,
  atRiskCount: number,
  stageData: { name: string; value: number }[],
  statusData: { name: string; value: number }[]
) {
  const guestList = guests.slice(0, 50);
  const displayName = (g: Guest) => `${g.first_name || ""} ${g.last_name || ""}`.trim() || g.name || "—";
  const stageRows = stageData.map((d) => `<tr><td>${d.name}</td><td class="text-right">${d.value}</td></tr>`).join("");
  const statusRows = statusData.map((d) => `<tr><td>${d.name}</td><td class="text-right">${d.value}</td></tr>`).join("");
  const guestRows = guestList.map((g) => `<tr><td>${displayName(g)}</td><td>${g.email || "—"}</td><td>${g.status || "—"}</td><td>${(g.journey_stage || g.journeyStage || "").replace(/_/g, " ")}</td><td>${g.is_at_risk || g.isAtRisk ? "Yes" : "No"}</td></tr>`).join("");
  return `<!DOCTYPE html><html><head><title>Church Analytics Report</title><style>body{font-family:system-ui,sans-serif;padding:2rem;font-size:14px;} table{width:100%;border-collapse:collapse;} th,td{border:1px solid #e5e7eb;padding:8px;text-align:left;} th{background:#f9fafb;font-weight:600;} .text-right{text-align:right;} h1{font-size:1.5rem;margin-bottom:0.5rem;} h2{font-size:1.1rem;margin:1.5rem 0 0.5rem;} .grid{display:grid;grid-template-columns:repeat(2,1fr);gap:1rem;margin-bottom:2rem;} .card{border:1px solid #e5e7eb;border-radius:8px;padding:1rem;} .card p:first-of-type{font-size:11px;text-transform:uppercase;color:#6b7280;} .card p:last-of-type{font-size:1.5rem;font-weight:700;}</style></head><body>
<h1>Church Analytics Report</h1>
<p style="color:#6b7280;margin-bottom:1.5rem">${new Date().toLocaleDateString("en-US", { dateStyle: "long" })}</p>
<div class="grid">
<div class="card"><p>Total Guests</p><p>${guests.length}</p></div>
<div class="card"><p>Retention Rate</p><p>${retentionRate}%</p></div>
<div class="card"><p>At-Risk</p><p>${atRiskCount}</p></div>
</div>
<h2>Journey Stage Distribution</h2><table><thead><tr><th>Stage</th><th class="text-right">Count</th></tr></thead><tbody>${stageRows}</tbody></table>
<h2>Status Breakdown</h2><table><thead><tr><th>Status</th><th class="text-right">Count</th></tr></thead><tbody>${statusRows}</tbody></table>
<h2>Guest List (first 50)</h2><table><thead><tr><th>Name</th><th>Email</th><th>Status</th><th>Stage</th><th>At Risk</th></tr></thead><tbody>${guestRows}</tbody></table>
<p style="margin-top:1.5rem;font-size:11px;color:#9ca3af">Generated by StewardOS</p>
</body></html>`;
}

export default function PDFExport({ guests, retentionRate, atRiskCount, stageData, statusData }: Props) {
  const handlePrint = () => {
    const html = buildPrintHtml(
      guests as Guest[],
      retentionRate,
      atRiskCount,
      stageData,
      statusData
    );
    const win = window.open("", "_blank");
    if (win) {
      win.document.write(html);
      win.document.close();
      win.focus();
      setTimeout(() => {
        win.print();
        win.close();
      }, 250);
    }
  };

  return (
    <button
      onClick={handlePrint}
      className="flex items-center gap-1.5 px-3 py-2 rounded-xl border border-gray-200 text-sm font-semibold text-[#6B7280] hover:border-[#C9A84C] hover:text-[#0A0A0A] transition-all"
    >
      <FileDown size={14} /> <span className="hidden sm:inline">PDF</span>
    </button>
  );
}
